keycloak_db_username: myuser
keycloak_db_password: mypassword
keycloak_db_host: db.example.com
keycloak_db_port: 5432
keycloak_db_name: keycloak

keycloak_admin_user: admin
keycloak_admin_password: adminpass

keycloak_ns: keycloak
keycloak_hostname: https://keycloak.example.com
keycloak_domain: keycloak.example.com

keycloak_image: quay.io/keycloak/keycloak
keycloak_image_tag: 26.0
keycloak_log_level: INFO
keycloak_proxy_address_forwarding: true
keycloak_jdbc_params: connectTimeout=21600
keycloak_login_listener_api_service_host: http://de-register-api-service
keycloak_login_listener_client_ids: de-prod

keycloak_resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi
