key_db_username: myuser
key_db_password: mypassword
key_admin_user: admin
key_admin_password: adminpass
key_db_name: keycloak
key_ns: keycloak
keycloak_hostname: https://keycloak.example.com
keycloak_domain: keycloak.example.com
key_db_host: db.example.com
key_db_port: 5432

keycloak_image: quay.io/keycloak/keycloak
keycloak_image_tag: 26.0
keycloak_log_level: INFO
keycloak_proxy_address_forwarding: true
keycloak_jdbc_params: connectTimeout=21600
keycloak_login_listener_api_service_host: http://de-register-api-service
keycloak_login_listener_client_ids: de-prod
