# for more ready policies:
# https://github.com/kyverno/policies/tree/main

# ---------------------------------------------------------------------------
# Prevent default project in Argo CD Applications
# ---------------------------------------------------------------------------

- name: Apply Kyverno ValidatingPolicy to prevent default project in Argo CD Applications
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: policies.kyverno.io/v1
      kind: ValidatingPolicy
      metadata:
        name: application-prevent-default-project
        annotations:
          policies.kyverno.io/title: Prevent Use of Default Project
          policies.kyverno.io/category: Argo
          policies.kyverno.io/severity: medium
          policies.kyverno.io/subject: Application
          policies.kyverno.io/description: >
            This policy prevents the use of the default project in an Argo CD Application.

      spec:
        validationActions:
          - Deny

        evaluation:
          background:
            enabled: true

        matchConstraints:
          resourceRules:
            - apiGroups:
                - argoproj.io
              apiVersions:
                - v1alpha1
              operations:
                - CREATE
                - UPDATE
              resources:
                - applications

        validations:
          - expression: "object.spec.project != 'default'"
            message: "The default project may not be used in an Argo CD Application."
