loki_helm_version: 17.3.4
loki_namespace: monitoring
loki_replicas: 1
loki_auth_enabled: false
loki_bucket_chunks: loki-chunks
loki_bucket_ruler: loki-ruler
loki_bucket_admin: loki-admin
loki_s3_endoint: seaweed-seaweedfs-s3.seaweed.svc.cluster.local:8333
loki_s3_secret_key: YOUR_SECRET_KEY
loki_s3_access_keyId: YOUR_ACCESS_KEYID
loki_s3_forcePathStyle: true
loki_s3_insecure: true
loki_gateway_enable: true
loki_gateway_ingress_enable: false
loki_gateway_ingress_host: gatewayloki.example.com
