rook_csi_driver_helm_version: 1.0.5
rook_helm_version: v1.20.7
ceph_ingress_enabled: false
ceph_dashboard_hostname: ceph-dashboard.example.com
dashboard_prometheusEndpoint: http://kube-prometheus-stack-prometheus.monitoring.svc:9090

# nodes and its disks device names
ceph_storage_nodes: {}
# ceph_storage_nodes:
#   - name: "cy-condor01"
#     devices:
#       - name: "sdb"

#   - name: "cy-agent01-k3s"
#     devices:
#       - name: "sdb"

#   - name: "cy-agent02-k3s"
#     devices:
#       - name: "sdb"

#   - name: "cy-k8w03"
#     devices:
#       - name: "sdd"
