---
- name: Ensure Rook values directory exists
  ansible.builtin.file:
    path: /tmp/rook
    state: directory
    mode: "0755"

- name: Render Rook cluster values file
  ansible.builtin.template:
    src: values.yaml.j2
    dest: /tmp/rook/values.yaml
    mode: "0644"

- name: Add Rook Helm repo
  kubernetes.core.helm_repository:
    name: rook-release
    repo_url: https://charts.rook.io/release

- name: Add Ceph-CSI Operator Helm repo
  kubernetes.core.helm_repository:
    name: ceph-csi-operator
    repo_url: https://ceph.github.io/ceph-csi-operator

# Starts the Ceph Operator, which will watch for Ceph CRs (custom resources).
- name: Install or upgrade Rook operator
  kubernetes.core.helm:
    name: rook-ceph
    chart_ref: rook-release/rook-ceph
    chart_version: "{{ rook_helm_version }}"
    release_namespace: rook-ceph
    create_namespace: true
    state: present

# Wait for Rook Ceph Operator to be ready
- name: Wait for Rook Ceph Operator to be ready
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    namespace: rook-ceph
    name: rook-ceph-operator
  register: rook_operator
  retries: 30
  delay: 10
  until: >
    rook_operator.resources | length > 0 and
    (
      rook_operator.resources[0].status.availableReplicas | default(0)
    ) == 1

# Rook's recommended CSI values must be used.
- name: Download Rook recommended Ceph-CSI values
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/rook/rook/{{ rook_helm_version }}/deploy/charts/ceph-csi-drivers/values.yaml"
    dest: /tmp/rook/ceph-csi-values.yaml
    mode: "0644"

# Installs the Ceph-CSI drivers to provision and mount RBD/CephFS volumes.
- name: Install or upgrade Ceph-CSI drivers
  kubernetes.core.helm:
    name: ceph-csi-drivers
    chart_ref: ceph-csi-operator/ceph-csi-drivers
    chart_version: "{{ rook_csi_driver_helm_version }}"
    release_namespace: rook-ceph
    create_namespace: true
    values_files:
      - /tmp/rook/ceph-csi-values.yaml
    state: present

# # Wait for Ceph CSI pods to be ready
# - name: Wait for Ceph CSI pods to be ready
#   kubernetes.core.k8s_info:
#     api_version: v1
#     kind: Pod
#     namespace: rook-ceph
#     label_selectors:
#       - app.kubernetes.io/part-of=ceph-csi
#   register: ceph_csi_pods
#   retries: 30
#   delay: 10
#   until: >
#     ceph_csi_pods.resources | length > 0 and
#     (
#       ceph_csi_pods.resources
#       | selectattr('status.phase', 'equalto', 'Running')
#       | list
#       | length
#     ) == (
#       ceph_csi_pods.resources | length
#     )

# Creates the CephCluster CR that the Rook operator will configure.
- name: Install or upgrade rook-ceph-cluster
  kubernetes.core.helm:
    name: rook-ceph-cluster
    chart_ref: rook-release/rook-ceph-cluster
    chart_version: "{{ rook_helm_version }}"
    release_namespace: rook-ceph
    create_namespace: true
    values_files:
      - /tmp/rook/values.yaml
    state: present

# Wait for CephCluster to become Ready
- name: Wait for CephCluster to be ready
  kubernetes.core.k8s_info:
    api_version: ceph.rook.io/v1
    kind: CephCluster
    namespace: rook-ceph
    name: rook-ceph
  register: ceph_cluster
  retries: 60
  delay: 15
  until: >
    ceph_cluster.resources | length > 0 and
    ceph_cluster.resources[0].status.phase | default('') == 'Ready'
